### ISSUE TITLE
Make tabs linkable

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1032]
**Is your feature request related to a problem? Please describe.**

This is mostly an issue for our language tabs in the `how-tos`, but could get applied on all tabs imo: https://github.com/facebook/docusaurus/pull/8225

**Comment by Dr-Electron** [comment]
https://docusaurus.io/docs/markdown-features/tabs#query-string

**Comment by jlvandenhout** [comment]
I have to unify the tabs to have consistent linking. So I'll unify all tabs configurations throughout the Wiki and add linking.
