### ISSUE TITLE
Improve new switcher implementation

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1060]
**Is your feature request related to a problem? Please describe.**

We need to refactor the Switcher to be easier configurable. Also it would be nice to have static items in the sidebar

**Comment by Dr-Electron** [comment]
Partially fixed in https://github.com/iotaledger/iota-wiki/pull/1082

**Comment by jlvandenhout** [comment]
This is now a bit too broad in my opinion. Let's discuss the current setup now that we are working with it and make explicit where we would like to see improvements.
