### ISSUE TITLE
One Plugin to Rule Them All

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1083]
**Is your feature request related to a problem? Please describe.**

Currently the wiki is a multi plugin system because of the way we imported docs in the old version.
Now with the merge being done, we should work on removing most of the plugins. This will:
- Make it possible to use relative links everywhere in the wiki
- Make it easier to use plugins in all sections
- Make client redirects possible in all sections
- Simplify a lot of other setups

**Additional context**

This means we need to change the code of plugin driven components like the switcher. And we might loose some nice features Docusaurus provides for plugins, like the version banners for example

**Comment by luca-moser** [comment]
Add pro/cons list to this issue so we know what to do.

**Comment by Dr-Electron** [comment]
| Pros                                                                                                                      | Cons                                                                                |
|---------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
| We can use relative linke (./relative/link.md) which automatically get autocompleted by editors and checked by docusaurus | We need to refactor components that depend on plugins like versions, custom banners |
|                                                                                                                           |                                                                                     |
|                                                                                                                           |                                                                                     |

**Comment by Dr-Electron** [comment]
It might makes sense to re-evaluate this as we need to redo our versioning system with Docusaurus v3

**Comment by lucas-tortora** [comment]
Keep https://github.com/iotaledger/devx/issues/356 in mind

**Comment by lucas-tortora** [comment]
No longer necessary in the new docs
