### ISSUE TITLE
Swizzle Versioning banners

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1087]
**Is your feature request related to a problem? Please describe.**

We should swizzle(?) the versioning banner to mark our docs as for example deprecated.
But maybe it would be easier to create a new component and wrap the docs content. That way in the plugin we could specify a custom text even.

**Comment by jlvandenhout** [comment]
Fixed in https://github.com/iotaledger/iota-wiki/commit/57585605123e52119386fe0acbfd7645b2e522ae
