### ISSUE TITLE
Wrong information provided

### ISSUE THREAD

**Issue by guhyeonjeong** [iotaledger/iota-wiki#1115]
**Describe the bug**
Wrong(probably outdated) information is provided in this link:
https://wiki.iota.org/shimmer/learn/smart-contracts/smart-contracts-community-tutorials/

**To Reproduce**
1. visit the link: 
https://wiki.iota.org/shimmer/learn/smart-contracts/smart-contracts-community-tutorials/

2. click the first document link which is written by ZAIRED

3. Wrong information is described

** Additional note **
I didn't check the second document, but it would probably provide some wrong information too.

**Comment by anistark** [comment]
Yes this is outdated and this entire section is subject to be removed completely.

cc: @lucas-tortora

**Comment by Dr-Electron** [comment]
Was removed in the restructure
