### ISSUE TITLE
Restructure introduction docs

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1119]
**Is your feature request related to a problem? Please describe.**

We should integrate the introduction docs nicer as mentioned in https://github.com/iotaledger/iota-wiki/pull/1118. The should probably even part of the learn section directly in some form

**Comment by luca-moser** [comment]
Lets check what we still need from these two sections to be put into "Learn" under protocols.
https://wiki.iota.org/introduction/welcome/
https://wiki.iota.org/introduction/stardust/explanations/ledger/nft/

**Comment by lucas-tortora** [comment]
Though the contet has pretty good explanations in between learn and a TIP, I can't actually find a good place without bloating up the wiki with redundant information.
