### ISSUE TITLE
SDK getting started sections should import examples code

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-wiki#1139]
**Is your feature request related to a problem? Please describe.**
SDK getting started sections should import examples code and don't have the code in the .md file itself.
Examples get not checked in the .md file and can easily get outdated.

**Describe the solution you'd like**
Import the code from an actual example as in the how-tos.

**Describe alternatives you've considered**
Remove them completely :trollface:

**Additional context**
https://github.com/iotaledger/iota-wiki/pull/1138

**Comment by jlvandenhout** [comment]
We had this at some point, I added them in https://github.com/iotaledger/iota-sdk/pull/40 . Not sure of the reason why this got removed?

**Comment by Thoralf-M** [comment]
Not sure why it got removed, but the example are now ready again
