### ISSUE TITLE
Improve the Switcher UX

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1253]
The Switcher needs some love. Some people have a hard time figuring out how it works and that it is even there 😅 

- [ ] Improve Design and make more visible/understandable
- [ ] Improve labeling UX for deprecated and network docs. Currently there is for example no way to see which networks a library supports if there is only one version as we hide the version dropdown with the tags in that case

**Comment by begonaalvarezd** [comment]
The switcher is in
- Build https://wiki.iota.org/build/welcome/
- Maintain https://wiki.iota.org/maintain/welcome/

People reading the documentation are having a hard time understanding this switcher. The reference was this website https://docs.dyte.io/ui-kit but its not the same use case in the wiki, so we need to give it a thought

We need to study how to improve this and them implement the change.

**Comment by jlvandenhout** [comment]
I think the current dropdown approach to choosing docs and versions is counterintuitive. We always link to a default doc and version when navigating to a subsection (i.e. SDK 1.0 when navigating to Build -> Layer 1) and you have to actively expand the dropdowns to discover additional docs and versions. I think this could be solved by having a kind of nested harmonica style switcher where docs are expanded when navigating to a subsection (so when navigating to Build -> Layer 1, the harmonica of docs in Layer 1 would be expanded) giving an instant overview of docs available. Same could be done for versions when navigating to a doc, but I guess there the current default version approach would suffice, but it's something we could test and compare.
