### ISSUE TITLE
Add possibility to ignore `Archived` versions

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1256]
**Is your feature request related to a problem? Please describe.**

Plugins version with an `Archived` badge should get ignored by the switcher. This allows us to not show Deprecated docs in the switcher before we remove them completely

**Comment by Dr-Electron** [comment]
Would this mean our release cycle for Wiki docs is something like:

- Testnet
    - Not a default version but can be selected in Switcher. Properly indexed?
- Shimmer
    - Default version for Shimmer. But needs to be selected in Switcher. Properly indexed
- IOTA
    - Default version also in Switcher. Properly indexed
- Deprecated
    - Still shows up in Switcher. Get's deprecated banner. Should not get indexed anymore.
- Archived
    - Does not show up in Switcher. Has deprecated banner. Not indexed
- Deleted
    - This are not the docs you are looking for

Do we even need Archived? Or do we just delete after it was Deprecated for a while?

**Comment by lucas-tortora** [comment]
I think everything after Deprecated is unnecessary. I'd like to keep the docs limited to things that run on an IOTA network. So, in this case, since nothing runs Chrysalis anymore, the Chrysalis build and maintain docs only add confusion. 

The same could be argued about the Learn docs, though those could be seen as an evolution of the protocol, a bit of history per se.

**Comment by Dr-Electron** [comment]
That would mean i can close this issue?

Because then the docs would always show up in the switcher and after they are deprecated for a while, they will just get deleted.

So having the archieved badge would only help if we want to keep the links up without mentioning the docs in the wiki for a little while. But for that time we already had them deprecated, right?

**Comment by Dr-Electron** [comment]
Ok, I think that means I can close it again @lucas-tortora and @jlvandenhout, right? 😅

**Comment by lucas-tortora** [comment]
> Ok, I think that means I can close it again @lucas-tortora and @jlvandenhout, right? 😅

Yup
