### ISSUE TITLE
[CCR]: Avoid search results to non-existing pages

### ISSUE THREAD

**Issue by GnrGnr** [iotaledger/iota-wiki#1533]
### Request Type

Modify Content

### Content Type

Other

### Wiki Section Target

Other

### Layer

Not Applicable

### Content Plan Checked

- [ ] Yes
- [X] No

### Link Breakage

- [ ] Yes
- [ ] No

### Description

I often run into the issue that search results are displayed that, when followed, lead to non-existent pages. Those pages in turn then offer alternative pages (which do exist). If we save search terms somewhere, maybe the search results for high-frequency search terms could be checked?

**Comment by Dr-Electron** [comment]
This is related to #857 .
Triggered it manually for now
