### ISSUE TITLE
Mention multicall3 support

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1536]
As requested by @Phyloiota we should mention that IOTA EVM supports multicall3

Additional info:
https://iota-evm.blockscout.com/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract
https://github.com/mds1/multicall/issues/251#issuecomment-2060062759
https://www.multicall3.com/deployments

**Comment by lucas-tortora** [comment]
Please expand on the article. It should cover:

* what it is
* use cases
* benefits
* a link to the project

Something like https://iota-wiki-prmctmgs3-iota1.vercel.app/build/subgraphs/ or https://iota-wiki-prmctmgs3-iota1.vercel.app/build/oracles/

**Comment by vivekjain23** [comment]
Raised a PR, which includes pages for multicall and multiSig wallet in the EVM tools section.

https://github.com/iotaledger/iota-wiki/pull/1537
