### ISSUE TITLE
Check for wasp doc updates

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1565]
**Describe the solution you'd like**

As wasp was updated from 1.0 to 1.2 we should check what changed and if how-tos need updates.

**Comment by lucas-tortora** [comment]
closed in favour of https://github.com/iotaledger/iota-wiki/issues/1570 and https://github.com/iotaledger/iota-wiki/issues/1571

**Comment by lucas-tortora** [comment]
closed in favour of https://github.com/iotaledger/iota-wiki/issues/1570 and https://github.com/iotaledger/iota-wiki/issues/1571
