### ISSUE TITLE
Add Tutorial: Cross-Chain NFT Market place

### ISSUE THREAD

**Issue by salaheldinsoliman** [iotaledger/iota-wiki#1625]
**Describe the solution you'd like**
This is meant to be a tutorial targeting areas ISC developers find particularly tricky, because of the differences between ISC and a normal EVM (core contracts and magic contract).

**Idea**
An NFT marketplace, where the NFTs are on: L1, ShimmerEVM Testnet and BNBTesnet

**Comment by lucas-tortora** [comment]
part 2 in https://github.com/iotaledger/iota-wiki/issues/1651
