### ISSUE TITLE
Style guide: versioning

### ISSUE THREAD

**Issue by aleksei-korolev** [iotaledger/iota-wiki#654]
**Describe the solution you'd like**
Add style guidelines on how to write documentation on different versions.

**Additional context**
@Dr-Electron @jlvandenhout could you please write step-by-step what do I have to do to introduce a second version of my project to the wiki?

**Comment by Dr-Electron** [comment]
Closing in favour of https://github.com/iotaledger/iota-wiki/issues/1120 😅
