### ISSUE TITLE
Landing page navigation overhaul

### ISSUE THREAD

**Issue by aleksei-korolev** [iotaledger/iota-wiki#691]
The current landing page is confusing:

The first box mentions "The complete reference for IOTA and Shimmer", but provides links for learning about IOTA (not Shimmer) and libraries (in the IOTA version by default).

Also that the "Start building" button jumps to the "Libraries" section is weird because there is a "Start building" section.

There is no clear indication that "Nodes and extensions" section is also technical/for developers.

**Comment by jlvandenhout** [comment]
Closing as out of date.
