### ISSUE TITLE
Restructure into IOTA, Shimmer, and Next

### ISSUE THREAD

**Issue by jlvandenhout** [iotaledger/iota-wiki#729]
This is a tracking issue for the restructure and separation into IOTA-, Shimmer-, and Next-specific environments. This will allow:

- A separate landing page, navbar, and theme per environment:
  - #631
  - #691
  - #693
  - #709
- A more clear indication of what content and what versions of projects belong to which environments:
  - #631
  - #692
- A more logical navigational structure and reduction in content:
  - #660
  - #694
  - #709
  - #710
 
Questions:
1. Should we remove FAQ's under about? It's just an aggregator.
2. Now that we have the `iota-wiki` organization, should we have a separate `tutorial` repo?

Related TODOs:
- [x] Relocate blog to its own repo.
~- [ ] Relocate media library to its own repo.~ Not relevant anymore with the current restructure.
- [x] Remove `Future` after split.
~- [ ] Remove `Networks` after split.~ Doesn't need to be removed as we still have different networks in each environment.

Restructure TODOs:
- [x] Create two directories under `content` directory: `iota`, and `common`.
- [x] Replicate new and applicable structure under each environment directory for internal documentation.
- [x] Add an `external` directory to each environment. Any applicable external documentation, and associated versions, will be located here as submodules.
- [x] Remove any remaining content from the repo.
- [x] Update `sidebars.js` files to represent new structure.
- [x] Update `package.json` and `docusaurus.config.js` files to represent new structure.
- [x] Update navbar configuration to new structure.
- [x] Copy `iota` directory content to `shimmer` and `next`.
- [x] Update `shimmer` and `next` to represent their applicable states.

**Comment by Dr-Electron** [comment]
Ser. This is out of date :trollface:
