### ISSUE TITLE
Versioning Problem - Merge conflicts with docusaurus.config

### ISSUE THREAD

**Issue by huhn511** [iotaledger/iota-wiki#737]
**Describe the bug**

For the versioning, we need different docusaurus.conig files for each version. We using a branch for a version, so `master/main/production` and `develop` has its own documentation.

For example: 
- [wallet.rs production](https://github.com/iotaledger/wallet.rs/blob/production/documentation/docusaurus.config.js)
- [wallet.rs develop](https://github.com/iotaledger/wallet.rs/blob/develop/documentation/docusaurus.config.js)

If the developers want to merge the `develop` branch into `master/main/production`, they also override the docusaurus.config file, which results in a wiki build error. 

A possible fix would be: 

- Moving the "custom settings" like id, label and editUrl to the wiki repo
- or write a tool/function wich gets the branch name, and  use it for the id, label and editUrl 
-  (use gitignore?) 

What do you think?

**Comment by jlvandenhout** [comment]
@Dr-Electron @lucas-tortora This should now be irrelevant after the merge. Any considerations before closing?

**Comment by Dr-Electron** [comment]
No, can be closed

**Comment by jlvandenhout** [comment]
Closed as irrelevant now that virtually all content lives in this repo.
