### ISSUE TITLE
Broken links on the IOTA Streams libraries overview page

### ISSUE THREAD

**Issue by halask** [iotaledger/iota-wiki#859]
On the top of the page https://wiki.iota.org/streams/libraries/overview/ the links to Rust, Wasm and C are broken ("page not found").

The error seems to be that the links go to (Rust example) https://wiki.iota.org/streams/libraries/overview/rust/getting_started/ while they should go to https://wiki.iota.org/streams/libraries/rust/getting_started/, i.e. without "/overview".

**Comment by Dr-Electron** [comment]
Fixed some time ago. Thanks for raising the issue ❤️
