### ISSUE TITLE
Add endpoints overview page

### ISSUE THREAD

**Issue by huhn511** [iotaledger/iota-wiki#874]
Add an overview page with all endpoints for Live and Testnetworks. 

Exapmle: https://wiki.polkadot.network/docs/maintain-endpoints

**Comment by Dr-Electron** [comment]
Should be fixed by moving the endpoints from the [introduction docs](https://wiki.iota.org/introduction/reference/networks/mainnet/) to the develop section of the wiki

**Comment by Dr-Electron** [comment]
This was done with d1611a7 but will keep this open to also add the ShimmerEVM endpoint I guess 🤔 
Wdyt? And how do we call that? ShimmerEVM testnet? 😓

**Comment by Dr-Electron** [comment]
Resolved in the restructure: https://wiki.iota.org/build/networks-endpoints/
