### ISSUE TITLE
Add a glossary to the wiki

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#878]
**Is your feature request related to a problem? Please describe.**

Once upon a time we wished for a glossary

**Describe the solution you'd like**

With long long hair our prince and saviour [rehype-jargon](https://github.com/freesewing/freesewing/tree/develop/packages/rehype-jargon) came for the rescue

**Describe alternatives you've considered**

We tried implanting this ourselves but I think Jargon solves all our problems 🤔

**Comment by Dr-Electron** [comment]
Blocked because I can't get it to work as this is an ESM module and Docusaurus doesn't like me 😢

Normally this should work like described in the note here: https://docusaurus.io/docs/markdown-features/plugins#installing-plugins

If this doesn't work with this plugin we would need to wait for official ESM support. (Which maybe already comes with version 3.0 which should be the next release 🤔 )

**Comment by luca-moser** [comment]
We defer this until the restructure is done given it will decrease the time needed to implement this significantly.

**Comment by Dr-Electron** [comment]
We can still work on it @luca-moser .
I just need @lucas-tortora help to clean up the glossary.
You wanted to post this comment on #993 🤣

**Comment by luca-moser** [comment]
Needs to be added to the current wiki and then to the restructure later.
