### ISSUE TITLE
Broken Link on Tutorial Page

### ISSUE THREAD

**Issue by anistark** [iotaledger/iota-wiki#906]
**Describe the bug**
Broken Link for Tutorial [Send Shimmer Tokens with Javascript](https://wiki.iota.org/shimmer/tutorials/send-shimmer-tokens-with-javascript)

**To Reproduce**

1. Go to [Tutorials Page](https://wiki.iota.org/shimmer/tutorials/)
2. Click on [Send Shimmer Tokens with Javascript](https://wiki.iota.org/shimmer/tutorials/send-shimmer-tokens-with-javascript)
3. See error.

**Comment by Dr-Electron** [comment]
Not relevant anymore
