### ISSUE TITLE
Allow the CodeSnippet component to break builds

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota-wiki#927]
**Is your feature request related to a problem? Please describe.**

I think it's worth considering the idea of allowing the CodeSnippet component to break wiki builds, so we can know anytime a snippet isn't working properly and correct it sooner rather than later.

**Describe the solution you'd like**
The component could raise an exception if `startString` or `endString` are not found./

**Comment by jlvandenhout** [comment]
I guess we can make it log to the console if that's the case, or make it a configurable setting. Breaking the entire Wiki build by default, because one code snippet is not properly configured sounds a bit rigorous to me.

**Comment by Dr-Electron** [comment]
Not relevant for now as we use another component
